### ISSUE TITLE
Repository URL in package.json is wrong

### ISSUE THREAD

**Issue by mgol** [sass-eyeglass/eyeglass-math#1]
Repository URL in package.json is wrong; it points to https://github.com/sass-eyeglass/eyeglass.git instead of https://github.com/sass-eyeglass/eyeglass-math.git. This makes it impossible to navigate from the npm module site to the repo where one could e.g. open an issue, look at the code etc. See how https://www.npmjs.com/package/eyeglass-math looks like.

**Comment by eoneill** [comment]
resolved with #4
